### PR TITLE
converting Options string value types to corresponding enum value types

### PR DESCRIPTION
**Pull request by zamgi**
(and other nonsense)

### CODE REVIEW

**Comment by GeorgeS2019** [comment]
@zamgi  

I do not speak for ZhongKaiFu.

It is great that you keep sending PRs and you care this project.

This repo has a discussion here
https://github.com/zhongkaifu/Seq2SeqSharp/discussions

The users here would like to know your feedback and in which way you would like this project to move forwards. 

Also we try to be respectful to each other. 

Please kindly not to use word like this 

> (and other **nonsense**)

 Sometimes others who are not used to that could feel uncomfortable.

Thank you for being active with this project. You are right, this is a good project

**Comment by zamgi** [comment]
@GeorgeS2019 

as you might have guessed, I do not use english for everyday communication (my native language is russian). when i say "nonsense", i mean what some changes in code who i made, doesn't change core of meaning, but make code most readable (from my point of view).
word "nonsense" is bad? which word is good?  (stuff?...)

**Comment by zamgi** [comment]
what i'm need, what i'm thinking? - i'm just work programmer (more then 20 years). its my job and its my hobby. i love it))
as i said, i'm think, what this project is great!

i have two question:
1) i'm append to exe-project files next lines:

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy &quot;..\dll\win_x64\sentencepiece.dll&quot; &quot;$(ProjectDir)\bin&quot;" />
    <Exec Command="copy &quot;..\dll\win_x64\libgcc_s_seh-1.dll&quot; &quot;$(ProjectDir)\bin&quot;" />
    <Exec Command="copy &quot;..\dll\win_x64\libgfortran-3.dll&quot; &quot;$(ProjectDir)\bin&quot;" />
    <Exec Command="copy &quot;..\dll\win_x64\libopenblas.dll&quot; &quot;$(ProjectDir)\bin&quot;" />
    <Exec Command="copy &quot;..\dll\win_x64\libquadmath-0.dll&quot; &quot;$(ProjectDir)\bin&quot;" />
  </Target>

but githab-build system raise error.
If run build in VS - everything is ok. 
what to do about it?

2)
what hardware do you use to train models? (what GPUs, how many pieces, how much video memory?)

**Comment by zhongkaifu** [comment]
For 1), that because build is in Linux environment, so it uses "cp" rather than "copy" for file copying. In addition, Seq2SeqSharp should support both Linux and Windows environment, but sentencepiece.dll and other dll files are for Windows only. We need to either make it configurable that users can enable/disable by themselves, or other solution that Seq2SeqSharp can run on both of these two operating systems.

For 2), There are various hardware users and I are using to run Seq2SeqSharp, such as Nvidia-DGX2 (V100 x 8), Linux machines with P100, P40, K80, TitanV and others.

**Pull request merged**
