### PR TITLE
converting model saving BinaryFormatter format to ProtoBuf format

### PR DESCRIPTION
**Pull request by zamgi**

### CODE REVIEW

**Comment by GeorgeS2019** [comment]
Can you visualize the saved models in ProtoBuf using Netron?

**Comment by zamgi** [comment]
> Can you visualize the saved models in ProtoBuf using Netron?
Hi @ GeorgeS2019, I don't know. I have never tried.

**Comment by zamgi** [comment]
> Can you visualize the saved models in ProtoBuf using Netron?

Hi @ GeorgeS2019, I don't know. I have never tried.

**Comment by zamgi** [comment]
> Can you visualize the saved models in ProtoBuf using Netron?

Hi @GeorgeS2019, I don't know. I have never tried.

**Comment by zamgi** [comment]
> Thanks @zamgi . Using ProtoBuf would be a great feature. I will take a look today.

Hi @zhongkaifu ! (U tool is great!) I broke your code formatting. This can make it difficult to understand the changes who i made.

**Pull request merged**
